# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8956-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter kenzo,$(TARGET_DEVICE)),)

endif
