# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mithorium-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter Mi8917 kenzo Mi439,$(TARGET_DEVICE)),)

endif
